#!/bin/bash

export PYTHONPATH=

source /reg/g/psdm/bin/conda_setup ""

args="$@"

SOURCE="${BASH_SOURCE[0]}"
# resolve $SOURCE until the file is no longer a symlink
while [ -h "$SOURCE" ]; do 
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" 
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

#ipython -i -c "%run $DIR/../lib/python2.7/site-packages/PyDataSource/ixarray.py $args" --pylab
ipython -i -c "%run $DIR/../python/PyDataSource/ixarray.py $args" --pylab


