
// *** Do not edit this file, it is auto-generated ***

#include "pdsdata/psddl/arraychar.ddl.h"

#include <iostream>
namespace Pds {
namespace Arraychar {
} // namespace Arraychar
} // namespace Pds
