
// *** Do not edit this file, it is auto-generated ***

#include "psddl_pds2psana/pixis.ddl.h"

#include <cstddef>

#include <stdexcept>

namespace psddl_pds2psana {
namespace Pixis {
Psana::Pixis::ConfigV1::GainMode pds_to_psana(Pds::Pixis::ConfigV1::GainMode e)
{
  return Psana::Pixis::ConfigV1::GainMode(e);
}

Psana::Pixis::ConfigV1::AdcMode pds_to_psana(Pds::Pixis::ConfigV1::AdcMode e)
{
  return Psana::Pixis::ConfigV1::AdcMode(e);
}

Psana::Pixis::ConfigV1::TriggerMode pds_to_psana(Pds::Pixis::ConfigV1::TriggerMode e)
{
  return Psana::Pixis::ConfigV1::TriggerMode(e);
}

ConfigV1::ConfigV1(const boost::shared_ptr<const XtcType>& xtcPtr)
  : Psana::Pixis::ConfigV1()
  , m_xtcObj(xtcPtr)
{
}
ConfigV1::~ConfigV1()
{
}


uint32_t ConfigV1::width() const {
  return m_xtcObj->width();
}


uint32_t ConfigV1::height() const {
  return m_xtcObj->height();
}


uint32_t ConfigV1::orgX() const {
  return m_xtcObj->orgX();
}


uint32_t ConfigV1::orgY() const {
  return m_xtcObj->orgY();
}


uint32_t ConfigV1::binX() const {
  return m_xtcObj->binX();
}


uint32_t ConfigV1::binY() const {
  return m_xtcObj->binY();
}


float ConfigV1::exposureTime() const {
  return m_xtcObj->exposureTime();
}


float ConfigV1::coolingTemp() const {
  return m_xtcObj->coolingTemp();
}


float ConfigV1::readoutSpeed() const {
  return m_xtcObj->readoutSpeed();
}


Psana::Pixis::ConfigV1::GainMode ConfigV1::gainMode() const {
  return pds_to_psana(m_xtcObj->gainMode());
}


Psana::Pixis::ConfigV1::AdcMode ConfigV1::adcMode() const {
  return pds_to_psana(m_xtcObj->adcMode());
}


Psana::Pixis::ConfigV1::TriggerMode ConfigV1::triggerMode() const {
  return pds_to_psana(m_xtcObj->triggerMode());
}


uint32_t ConfigV1::activeWidth() const {
  return m_xtcObj->activeWidth();
}


uint32_t ConfigV1::activeHeight() const {
  return m_xtcObj->activeHeight();
}


uint32_t ConfigV1::activeTopMargin() const {
  return m_xtcObj->activeTopMargin();
}


uint32_t ConfigV1::activeBottomMargin() const {
  return m_xtcObj->activeBottomMargin();
}


uint32_t ConfigV1::activeLeftMargin() const {
  return m_xtcObj->activeLeftMargin();
}


uint32_t ConfigV1::activeRightMargin() const {
  return m_xtcObj->activeRightMargin();
}


uint32_t ConfigV1::cleanCycleCount() const {
  return m_xtcObj->cleanCycleCount();
}


uint32_t ConfigV1::cleanCycleHeight() const {
  return m_xtcObj->cleanCycleHeight();
}


uint32_t ConfigV1::cleanFinalHeight() const {
  return m_xtcObj->cleanFinalHeight();
}


uint32_t ConfigV1::cleanFinalHeightCount() const {
  return m_xtcObj->cleanFinalHeightCount();
}


uint32_t ConfigV1::maskedHeight() const {
  return m_xtcObj->maskedHeight();
}


uint32_t ConfigV1::kineticHeight() const {
  return m_xtcObj->kineticHeight();
}


float ConfigV1::vsSpeed() const {
  return m_xtcObj->vsSpeed();
}


int16_t ConfigV1::infoReportInterval() const {
  return m_xtcObj->infoReportInterval();
}


uint16_t ConfigV1::exposureEventCode() const {
  return m_xtcObj->exposureEventCode();
}


uint32_t ConfigV1::numIntegrationShots() const {
  return m_xtcObj->numIntegrationShots();
}


uint32_t ConfigV1::frameSize() const {
  return m_xtcObj->frameSize();
}


uint32_t ConfigV1::numPixelsX() const {
  return m_xtcObj->numPixelsX();
}


uint32_t ConfigV1::numPixelsY() const {
  return m_xtcObj->numPixelsY();
}


uint32_t ConfigV1::numPixels() const {
  return m_xtcObj->numPixels();
}

template <typename Config>
FrameV1<Config>::FrameV1(const boost::shared_ptr<const XtcType>& xtcPtr, const boost::shared_ptr<const Config>& cfgPtr)
  : Psana::Pixis::FrameV1()
  , m_xtcObj(xtcPtr)
  , m_cfgPtr(cfgPtr)
{
}
template <typename Config>
FrameV1<Config>::~FrameV1()
{
}


template <typename Config>
uint32_t FrameV1<Config>::shotIdStart() const {
  return m_xtcObj->shotIdStart();
}


template <typename Config>
float FrameV1<Config>::readoutTime() const {
  return m_xtcObj->readoutTime();
}


template <typename Config>
float FrameV1<Config>::temperature() const {
  return m_xtcObj->temperature();
}


template <typename Config>
ndarray<const uint16_t, 2> FrameV1<Config>::data() const {
  return m_xtcObj->data(*m_cfgPtr, m_xtcObj);
}

template class FrameV1<Pds::Pixis::ConfigV1>;
} // namespace Pixis
} // namespace psddl_pds2psana
