
// *** Do not edit this file, it is auto-generated ***

#include "psddl_pds2psana/rayonix.ddl.h"

#include <cstddef>

#include <stdexcept>

namespace psddl_pds2psana {
namespace Rayonix {
Psana::Rayonix::ConfigV1::ReadoutMode pds_to_psana(Pds::Rayonix::ConfigV1::ReadoutMode e)
{
  return Psana::Rayonix::ConfigV1::ReadoutMode(e);
}

ConfigV1::ConfigV1(const boost::shared_ptr<const XtcType>& xtcPtr)
  : Psana::Rayonix::ConfigV1()
  , m_xtcObj(xtcPtr)
{
}
ConfigV1::~ConfigV1()
{
}


uint8_t ConfigV1::binning_f() const {
  return m_xtcObj->binning_f();
}


uint8_t ConfigV1::binning_s() const {
  return m_xtcObj->binning_s();
}


uint32_t ConfigV1::exposure() const {
  return m_xtcObj->exposure();
}


uint32_t ConfigV1::trigger() const {
  return m_xtcObj->trigger();
}


uint16_t ConfigV1::rawMode() const {
  return m_xtcObj->rawMode();
}


uint16_t ConfigV1::darkFlag() const {
  return m_xtcObj->darkFlag();
}


Psana::Rayonix::ConfigV1::ReadoutMode ConfigV1::readoutMode() const {
  return pds_to_psana(m_xtcObj->readoutMode());
}


const char* ConfigV1::deviceID() const {
  return m_xtcObj->deviceID();
}


uint32_t ConfigV1::pixelWidth() const {
  return m_xtcObj->pixelWidth();
}


uint32_t ConfigV1::pixelHeight() const {
  return m_xtcObj->pixelHeight();
}


uint32_t ConfigV1::maxWidth() const {
  return m_xtcObj->maxWidth();
}


uint32_t ConfigV1::maxHeight() const {
  return m_xtcObj->maxHeight();
}


uint32_t ConfigV1::width() const {
  return m_xtcObj->width();
}


uint32_t ConfigV1::height() const {
  return m_xtcObj->height();
}


uint32_t ConfigV1::numPixels() const {
  return m_xtcObj->numPixels();
}

Psana::Rayonix::ConfigV2::ReadoutMode pds_to_psana(Pds::Rayonix::ConfigV2::ReadoutMode e)
{
  return Psana::Rayonix::ConfigV2::ReadoutMode(e);
}

ConfigV2::ConfigV2(const boost::shared_ptr<const XtcType>& xtcPtr)
  : Psana::Rayonix::ConfigV2()
  , m_xtcObj(xtcPtr)
{
}
ConfigV2::~ConfigV2()
{
}


uint8_t ConfigV2::binning_f() const {
  return m_xtcObj->binning_f();
}


uint8_t ConfigV2::binning_s() const {
  return m_xtcObj->binning_s();
}


int16_t ConfigV2::testPattern() const {
  return m_xtcObj->testPattern();
}


uint32_t ConfigV2::exposure() const {
  return m_xtcObj->exposure();
}


uint32_t ConfigV2::trigger() const {
  return m_xtcObj->trigger();
}


uint16_t ConfigV2::rawMode() const {
  return m_xtcObj->rawMode();
}


uint16_t ConfigV2::darkFlag() const {
  return m_xtcObj->darkFlag();
}


Psana::Rayonix::ConfigV2::ReadoutMode ConfigV2::readoutMode() const {
  return pds_to_psana(m_xtcObj->readoutMode());
}


const char* ConfigV2::deviceID() const {
  return m_xtcObj->deviceID();
}


uint32_t ConfigV2::pixelWidth() const {
  return m_xtcObj->pixelWidth();
}


uint32_t ConfigV2::pixelHeight() const {
  return m_xtcObj->pixelHeight();
}


uint32_t ConfigV2::maxWidth() const {
  return m_xtcObj->maxWidth();
}


uint32_t ConfigV2::maxHeight() const {
  return m_xtcObj->maxHeight();
}


uint32_t ConfigV2::width() const {
  return m_xtcObj->width();
}


uint32_t ConfigV2::height() const {
  return m_xtcObj->height();
}


uint32_t ConfigV2::numPixels() const {
  return m_xtcObj->numPixels();
}

} // namespace Rayonix
} // namespace psddl_pds2psana
