
// *** Do not edit this file, it is auto-generated ***

#include <cstddef>
#include "psddl_psana/quadadc.ddl.h"
#include <iostream>
namespace Psana {
namespace QuadAdc {

ConfigV1::~ConfigV1() {}

} // namespace QuadAdc
} // namespace Psana
